# Generated by Django 4.2.7 on 2026-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final'), ('assignment', 'Assignment')], max_length=20)),
                ('score', models.FloatField()),
                ('total', models.FloatField(default=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
