# Generated by Django 4.2.7 on 2026-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('counseling', 'Counseling Session'), ('parent_meet', 'Parent Meeting'), ('academic_help', 'Academic Support'), ('behavior', 'Behavior Guidance'), ('escalation', 'Escalated to Admin')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('escalated', 'Escalated')], default='pending', max_length=15)),
                ('scheduled', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
